language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
  - ffmpeg -hwaccels
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config