- id: '1603938426639'
  alias: Cooking light auto turn off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  - platform: time_pattern
    minutes: /10
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.cooking_lights
      state: 'off'
    - condition: state
      entity_id: light.dining_lights_switch
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.kitchen_multi_illuminance
      above: '70'
    - condition: state
      entity_id: input_boolean.cooking_lights_auto
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.cooking_lights_auto
  mode: single
