- platform: template
  sensors:
    athome:
      friendly_name: "Someone at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nata', 'home')
           or is_state('person.nick', 'home')
           or is_state('input_boolean.guest_mode', 'on')}}

    nick_home:
      friendly_name: "Nick at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nick', 'home')}}

    nata_home:
      friendly_name: "Nata at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nata', 'home')}}

- platform: aarlo
  monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity
