- platform: template
  sensors:
    athome:
      friendly_name: "Someone at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nata', 'home')
           or is_state('person.nick', 'home')
           or is_state('person.alisa', 'home')
           or is_state('person.sasha', 'home')
           or is_state('person.alla', 'home')
           or is_state('input_boolean.guest_mode', 'on')}}

    nick_home:
      friendly_name: "Nick at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nick', 'home')}}

    nata_home:
      friendly_name: "Nata at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nata', 'home')}}

    all_windows_closed:
      friendly_name: "All windows closed"
      device_class: opening
      value_template: >-
        {{ is_state('binary_sensor.patio_door_contact', 'on')
          or is_state('binary_sensor.entrance_contact', 'on')
          or is_state('binary_sensor.garage_enter_contact', 'on') }}

- platform: aarlo
  monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity
