- platform: template
  sensors:
    athome:
      friendly_name: "Someone at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nata', 'home')
           or is_state('person.nick', 'home')}}

    nick_home:
      friendly_name: "Nick at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nick', 'home')}}

    nata_home:
      friendly_name: "Nata at home"
      device_class: occupancy
      value_template: >-
        {{ is_state('person.nata', 'home')}}

    garage_closed:
      friendly_name: "Garage door closed"
      device_class: garage_door
      value_template: >-
        {{ is_state('cover.garage_door', 'open') }}

    all_windows_closed:
      friendly_name: "All windows closed"
      device_class: opening
      value_template: >-
        {{ is_state('binary_sensor.master_left_window_contact', 'on')
          or is_state('binary_sensor.livingroom_right_window_contact', 'on')
          or is_state('binary_sensor.kids_bedroom_right_window_contact', 'on')
          or is_state('binary_sensor.kitchen_patio_door_contact', 'on') }}

- platform: car_wash
  weather: weather.kash_daynight
  days: 5
