- platform: aarlo
  #ffmpeg_arguments: '-pred 1 -q:v 2'

- platform: generic
  name: "Deebot Live Map"
  still_image_url: "https://home.veritynh.dev/local/Liova_liveMap.png" #Example configuration for livemappath: 'www/live_map.png'
  verify_ssl: false
