# - platform: ffmpeg
#   name: Wyze Cam 1
#   still_image_url: http://192.168.1.254:8765/picture/1/current/
#   stream_source: http://192.168.1.254:18081
#   input: http://192.168.1.254:18081
#   extra_arguments: '-pred 1 -q:v 2'

- platform: mjpeg
  name: Wyze Cam 1
  still_image_url: http://192.168.1.254:8765/picture/1/current/
  mjpeg_url: http://192.168.1.254:18081

- platform: aarlo
  #ffmpeg_arguments: '-pred 1 -q:v 2'

- platform: generic
  name: "Deebot Live Map"
  still_image_url: "https://home.veritynh.dev/local/Liova_liveMap.png" #Example configuration for livemappath: 'www/live_map.png'
  verify_ssl: false