- platform: ffmpeg
  name: Garage cam
  input: !secret camera_garage_input
#- platform: generic
#  name: Garage cam
#  stream_source: !secret camera_garage_input
#  verify_ssl: false

- platform: badnest

- platform: aarlo
  ffmpeg_arguments: '-pred 1 -q:v 2'