#homeassistant: !include homeassistant.yaml
#
## Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#
##homeassistant: !include homeassistant.yaml
#
#config:
#history:
#logbook:
#map:
#mobile_app:
#ssdp:
#sun:
#system_health:
#updater:
#zeroconf:
#cloud:
#discovery:
#dhcp:

#lovelace:
#  mode: yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

zone:
#automation: !include_dir_list automation/

automation: !include automations.yaml

script: !include scripts.yaml

scene: !include scenes.yaml
#scene old: !include_dir_merge_list scenes/

#frontend: !include frontend.yaml

http: !include http.yaml

#tuya: !include tuya.yaml

ecovacs: !include ecovacs.yaml

#deebot: !include deebot.yaml

stream:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera: !include camera.yaml

light: !include light.yaml


# Person tracker
person:

device_tracker: !include device_tracker.yaml

sensor: !include sensors.yaml

#Dummy sensors
binary_sensor: !include binary_sensors.yaml

weather: !include weather.yaml

#smartweather:
#  station_id: !secret sm_station_id
#  api_key: !secret sm_api_key

#mqtt: !include mqtt.yaml

input_boolean: #!include_dir_named input_boolean/
input_number: #!include_dir_named input_number/
input_text:
input_datetime:
input_select:

#uilogs:

#speedtestdotnet:
#  scan_interval:
#    minutes: 15


google_assistant:
  project_id: hassintegration-695ba
  service_account: !include google/HASSIntegration-170c7741d7db.json
  report_state: true
  secure_devices_pin: !secret security_pin
  exposed_domains:
    - switch
    - light
    - fan
    - input_boolean
    - cover
  entity_config:
    light.living_room_lights:
      expose: false
    light.kids_bedroom_lights:
      expose: false
    light.master_bedroom_lights:
      expose: false
    light.corridor_lights:
       expose: false
    light.dining_lights_switch:
      expose: false
    light.cooking_lights:
      expose: false
    input_boolean.living_lights_auto:
      name: "Living auto mode"
      expose: false
      aliases:
        - "Living auto lights"
        - "Auto lights"
    input_boolean.kitchen_lights_auto:
      name: "Kitchen auto mode"
      expose: false
      aliases:
        - "Kitchen auto lights"
        - "Auto lights"
    input_boolean.cooking_lights_auto:
      expose: false
      name: "Cooking auto mode"
      aliases:
        - "Cooking auto lights"
        - "Auto lights"
    input_boolean.kids_lights_auto:
      expose: false
      name: "Kids auto mode"
      aliases:
        - "Kids auto lights"
        - "Auto lights"
    input_boolean.master_lights_auto:
      expose: false
      name: "Master auto mode"
      aliases:
        - "Master auto lights"
        - "Auto lights"

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  user_agent: linux

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
#    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 1

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id    # ("Project ID" in the Device Access Console)
  subscriber_id: !secret nest_subscriber_id # ("Subscription ID" in Google Cloud Console. Replace with full path.)

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
#  devices:
#    10008fd3ee:
#      name: Master Humidifier
#      device_class: switch

#media_player: !include spotify.yaml
#spotcast: !include spotcast.yaml
#yandex_smart_home_fix:

media_player:
  - platform: aarlo

yandex_smart_home:
  filter:
    include_entities:
      - climate.dining_room
      - light.cooking_lights
      - light.dining_lights_switch
      - light.living_room_lights
      - light.kids_bedroom_lights
      - light.master_bedroom_lights
      - light.corridor_lights
      - fan.master_air_purifier
      - switch.tv
      - vacuum.e200p8u2391901643866
      - vacuum.1st_floor_deebot
      - switch.sonoff_10009068c3
      - switch.sonoff_1000b91f0e
      - switch.sonoff_10008fd3ee
      - cover.garage_door

yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password
  recognition_lang: ru-RU

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token  # создайте своего Телеграм бота
    allowed_chat_ids:
      - !secret nick_telegram_id  # укажите ID своего аккаунта
      - !secret nata_telegram_id
      - !secret home_telegram_group
#      - TELEGRAM_USER2_ID  # при желании, поддерживается несколько аккаунтов

upnp:
  local_ip: 192.168.1.2

conversation:
  intents:
    media_player.yandex_station_ff98f029bceb4110b4b81659: [.+]

#logger:
#  default: warning
#  logs:
#    homeassistant.components.wiz_light: debug
