homeassistant: !include homeassistant.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

#homeassistant: !include homeassistant.yaml

config:
history:
logbook:
map:
mobile_app:
ssdp:
sun:
system_health:
updater:
zeroconf:
cloud:

lovelace:
  mode: yaml        

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

zone: !include zones.yaml

automation: !include_dir_list automation/

script: !include scripts.yaml

scene: !include scenes.yaml
scene old: !include_dir_merge_list scenes/

frontend: !include frontend.yaml

http: !include http.yaml

tuya: !include tuya.yaml

ecovacs: !include ecovacs.yaml

stream:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera: !include camera.yaml

light: !include light.yaml

# Garage door
cover: !include garage.yaml

# Person tracker
#person: !include persons.yaml
person:

device_tracker: !include device_tracker.yaml

# Nest integration ???
badnest: !include nest.yaml

climate: !include thermostat.yaml

sensor: !include sensors.yaml

#Dummy sensors
binary_sensor: !include binary_sensors.yaml

weather: !include weather.yaml

mqtt: !include mqtt.yaml

input_boolean: !include_dir_named input_boolean/
input_number: !include_dir_named input_number/

uilogs:

#media_player: !include spotify.yaml
#spotcast: !include spotcast.yaml

#logger:
#  default: info
#  logs:
#    homeassistant.components.smartthings: debug
