#homeassistant: !include homeassistant.yaml
#
## Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#
##homeassistant: !include homeassistant.yaml
#
#config:
#history:
#logbook:
#map:
#mobile_app:
#ssdp:
#sun:
#system_health:
#updater:
#zeroconf:
#cloud:
#discovery:
#dhcp:

#lovelace:
#  mode: yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

zone:
#automation: !include_dir_list automation/

automation: !include automations.yaml

script: !include scripts.yaml

scene: !include scenes.yaml
#scene old: !include_dir_merge_list scenes/

#frontend: !include frontend.yaml

http: !include http.yaml

#tuya: !include tuya.yaml

ecovacs: !include ecovacs.yaml

#deebot: !include deebot.yaml

stream:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera: !include camera.yaml

light: !include light.yaml


# Person tracker
person:

device_tracker: !include device_tracker.yaml

sensor: !include sensors.yaml

#Dummy sensors
binary_sensor: !include binary_sensors.yaml

#smartweather:
#  station_id: !secret sm_station_id
#  api_key: !secret sm_api_key

#mqtt: !include mqtt.yaml

input_boolean: #!include_dir_named input_boolean/
input_number: #!include_dir_named input_number/
input_text:
input_datetime:
input_select:

#uilogs:

#speedtestdotnet:
#  scan_interval:
#    minutes: 15

alexa:
  smart_home:
    locale: en-US
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_entities:
        - light.breakfast_lamp
        - light.cooking_lamp
        - light.dining_lamp
        - light.kids_bedroom_lights
        - light.master_bedroom_lights
        - light.livingroom_lamp
        - light.hallway_lamp
        - light.laundry_lamp
        - fan.master_air_purifier
        - switch.livingroom_tv
        - vacuum.liova
    


nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id    # ("Project ID" in the Device Access Console)
  subscriber_id: !secret nest_subscriber_id # ("Subscription ID" in Google Cloud Console. Replace with full path.)

google_assistant:
  project_id: hassintegration-695ba
  service_account: !include google/HASSIntegration-170c7741d7db.json
  report_state: true
  secure_devices_pin: !secret security_pin
  expose_by_default: false
  entity_config:
    light.breakfast_lamp:
      expose: true
      name: "Breakfast lamp"
      aliases:
        - "Cat lamp"
    light.cooking_lamp:
      expose: true
      name: "Cooking lamp"
      aliases:
        - "Kitchen lamp"
    light.dining_lamp:
      expose: true
      name: "Dining lamp"
    light.kids_bedroom_lights:
       expose: true
       name: "Kids bedroom light"
       aliases:
         - "Kids lights"
    light.master_bedroom_lights:
      expose: true
      name: "Master bedroom light"
      aliases:
        - "Master lights"
    light.livingroom_lamp:
      expose: true
      name: "Livingroom lamp"
    light.hallway_lamp:
      expose: true
      name: "Hallway lamp"
    light.laundry_lamp:
      expose: true
      name: "Laundry lamp"
    fan.master_air_purifier:
      name: "Master purifier"
      expose: true
      aliases:
        - "Master air purifier"
    switch.livingroom_tv:
      name: "Living room TV"
      expose: true
      aliases:
        - "TV"
    climate.thermostat:
      expose: true
      name: "Thermostat"
    vacuum.liova:
      expose: true
      name: "Vacuum"
      aliases:
        - "Kraken"


aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  user_agent: linux

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
#    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 1

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
#  devices:
#    10008fd3ee:
#      name: Master Humidifier
#      device_class: switch

#media_player: !include spotify.yaml
#spotcast: !include spotcast.yaml
#yandex_smart_home_fix:

media_player:
  - platform: aarlo

yandex_smart_home:
  notifier:
    - oauth_token: !secret yandex_oauth_token
      skill_id: !secret yandex_skill_id
      user_id: !secret yandex_user_id_nick
    - oauth_token: !secret yandex_oauth_token
      skill_id: !secret yandex_skill_id
      user_id: !secret yandex_user_id_nata
  filter:
    include_entities:
      - light.breakfast_lamp
      - light.cooking_lamp
      - light.dining_lamp
      - light.livingroom_lamp
      - light.hallway_lamp
      - light.laundry_lamp
      - light.master_bedroom_lights
      - light.kids_bedroom_lights
      - vacuum.liova
      - fan.master_air_purifier
      - climate.thermostat
      - switch.livingroom_tv
  entity_config:
    ##########  СВЕТ ##############
    light.breakfast_lamp:
      name: "Бэкдор"
      room: Кухня
    light.cooking_lamp:
      name: "Кухня"
      room: Кухня
    light.dining_lamp:
      name: "Столовая"
      room: Столовая
    light.livingroom_lamp:
      name: "Гостиная"
      room: Гостиная
    light.hallway_lamp:
      name: "Прихожая"
      room: Прихожая
    light.laundry_lamp:
      name: "Прачечная"
      room: Прачечная
    light.master_bedroom_lights:
      name: "Главная спальня"
      room: Главная спальня
    light.kids_bedroom_lights:
      name: "Детская"
      room: Детская
    ########## Устройства ###############
    vacuum.liova:
      name: Пылесос
      room: Прихожая
    fan.master_air_purifier:
      name: "Очиститель воздуха"
      room: Главная спальня
    climate.thermostat:
      name: Термостат
      room: Гостиная
    switch.livingroom_tv:
      name: Телевизор
      room: Гостиная

yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password
  recognition_lang: ru-RU

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token  # создайте своего Телеграм бота
    allowed_chat_ids:
      - !secret nick_telegram_id  # укажите ID своего аккаунта
      - !secret nata_telegram_id
      - !secret home_telegram_group
#      - TELEGRAM_USER2_ID  # при желании, поддерживается несколько аккаунтов

upnp:
  local_ip: 192.168.1.2

conversation:
  intents:
    media_player.yandex_station_ff98f029bceb4110b4b81659: [.+]

#logger:
#  default: warning
#  logs:
#    homeassistant.components.wiz_light: debug
