- platform: composite
  name: nick_tracker
  time_as: device_or_local
  consider_home: 60
  entity_id:
    - binary_sensor.mykola_iankovskyi_s_galaxy_s10_presence

- platform: composite
  name: nata_tracker
  time_as: device_or_local
  consider_home: 60
  entity_id:
    - binary_sensor.natalia_yankovskaya_s_galaxy_note10_presence

