- platform: group
  name: Master Bedroom Lights
  entities:
    - light.master_fan_1
    - light.master_fan_2
    - light.master_fan_3
    - light.master_fan_4

- platform: group
  name: Kids Bedroom Lights
  entities:
    - light.kids_right_lamp
    - light.kids_left_lamp
