- platform: group
  name: Living Room Lights
  id: living_room_lights
  entities:
    - light.livingroom_left_lamp
    - light.livingroom_right_lamp

- platform: group
  name: Kids Bedroom Lights
  id: kids_bedroom_lights
  entities:
    - light.kids_left_lamp
    - light.kids_right_lamp

- platform: group
  id: master_bedroom_lights
  name: Master Bedroom Lights
  entities:
    - light.master_fan_1
    - light.master_fan_2
    - light.master_fan_3
    - light.master_fan_4

- platform: group
  id: corridor_lights
  name: Corridor Lights
  entities:
    - light.corridor_light

- platform: group
  id: kitchen_lights
  name: Kitchen Lights
  entities:
    - light.66514121500291c7eb5c
    - light.66514121500291c7eb85
    - light.66514121500291c7eb7a
    - light.66514121500291c7f072
    - light.66514121500291c7f036

- platform: wiz_light
  name: "Livingroom left lamp"
  host: "10.0.0.4"

- platform: wiz_light
  name: "Livingroom right lamp"
  host: "10.0.0.181"

- platform: wiz_light
  name: "Master fan 1"
  host: "10.0.0.190"

- platform: wiz_light
  name: "Master fan 2"
  host: "10.0.0.82"

- platform: wiz_light
  name: "Master fan 3"
  host: "10.0.0.249"

- platform: wiz_light
  name: "Master fan 4"
  host: "10.0.0.206"

- platform: wiz_light
  name: "Kids left lamp"
  host: "10.0.0.48"

- platform: wiz_light
  name: "Kids right lamp"
  host: "10.0.0.187"

- platform: wiz_light
  name: "Corridor light"
  host: "10.0.0.153"
