- platform: group
  name: Living Room Lights
  entities:
    - light.livingroom_left_lamp
    - light.livingroom_right_lamp

- platform: group
  name: Kids Bedroom Lights
  entities:
    - light.kids_right_lamp
    - light.kids_left_lamp

- platform: group
  name: Master Bedroom Lights
  entities:
    - light.master_fan_1
    - light.master_fan_2
    - light.master_fan_3
    - light.master_fan_4

- platform: group
  name: Corridor Lights
  entities:
    - light.corridor_lamp

- platform: group
  name: Kitchen Lights
  entities:
    - light.dining_lights_switch

- platform: group
  name: Cooking Lights
  entities:
    - light.cooking_lamp_1
    - light.cooking_lamp_2
#
#- platform: wiz_light
#  name: "Livingroom left lamp"
#  host: "192.168.1.200"
#
#- platform: wiz_light
#  name: "Livingroom right lamp"
#  host: "192.168.1.201"
#
#- platform: wiz_light
#  name: "Master fan 1"
#  host: "192.168.1.202"
#
#- platform: wiz_light
#  name: "Master fan 2"
#  host: "192.168.1.203"
#
#- platform: wiz_light
#  name: "Master fan 3"
#  host: "192.168.1.204"
#
#- platform: wiz_light
#  name: "Master fan 4"
#  host: "192.168.1.205"
#
#- platform: wiz_light
#  name: "Kids left lamp"
#  host: "192.168.1.206"
#
#- platform: wiz_light
#  name: "Kids right lamp"
#  host: "192.168.1.207"
#
#- platform: wiz_light
#  name: "Corridor light"
#  host: "192.168.1.208"
#
#- platform: wiz_light
#  name: "Cooking light 1"
#  host: "192.168.1.209"
#
#- platform: wiz_light
#  name: "Cooking light 2"
#  host: "192.168.1.210"