- platform: badnest

- platform: waze_travel_time
  name: "Nick to Work"
  origin: device_tracker.sm_g975u
  destination: zone.nick_work
  region: 'US'     

- platform: waze_travel_time
  name: "Nata to Work"
  origin: device_tracker.sm_n970u
  destination: zone.nata_work
  region: 'US'

- platform: waze_travel_time
  name: "Nick to Home"
  origin: device_tracker.sm_g975u
  destination: zone.home
  region: 'US'

- platform: waze_travel_time
  name: "Nata to Home"
  origin: device_tracker.sm_n970u
  destination: zone.home
  region: 'US'

- platform: min_max
  type: mean
  name: Average house temperature
  entity_ids:
    - sensor.kitchen_multi_temperature
    - sensor.livingroom_multi_temperature
    - sensor.kids_multy_temperature
    - sensor.master_multi_temperature

- platform: template
  sensors:
    nest_temperature:
      friendly_name: "Nest temperature"
      value_template: "{{ state_attr('climate.kitchen_thermostat', 'current_temperature') }}"
      device_class: temperature
      unit_of_measurement: °C

    nest_humidity:
      friendly_name: "Nest humidity"
      value_template: "{{ state_attr('climate.kitchen_thermostat', 'current_humidity') }}"
      device_class: humidity