#- platform: min_max
#  type: mean
#  name: Average house temperature
#  entity_ids:
#    - sensor.kitchen_multi_temperature
#    - sensor.livingroom_multi_temperature
#    - sensor.kids_multy_temperature
#    - sensor.master_multi_temperature

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, make sure configuration file is encoded as UTF-8
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

#- platform: template
#  sensors:
#    first_floor_lights:
#      friendly_name: "First floor light state"
#      value_template: >-
#        {% if (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.dining_lights_switch', 'off') and is_state('input_boolean.living_nightmode', 'off')) %}
#          living_right_on
#        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.dining_lights_switch', 'off') and is_state('input_boolean.living_nightmode', 'off')) %}
#          living_left_on
#        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.dining_lights_switch', 'off') and is_state('input_boolean.living_nightmode', 'on')) %}
#          living_nightmode
#        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.dining_lights_switch', 'on') and is_state('input_boolean.living_nightmode', 'on')) %}
#          kitchen_and_nightmode
#        {% elif (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.dining_lights_switch', 'off') and is_state('input_boolean.living_nightmode', 'off')) %}
#          living_all
#        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.dining_lights_switch', 'on') and is_state('input_boolean.living_nightmode', 'off')) %}
#          kitchen_on
#        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.dining_lights_switch', 'on') and is_state('input_boolean.living_nightmode', 'off')) %}
#          kitchen_and_left_on
#        {% elif (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.dining_lights_switch', 'on') and is_state('input_boolean.living_nightmode', 'off')) %}
#          kitchen_and_right_on
#        {% elif (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.dining_lights_switch', 'on') and is_state('input_boolean.living_nightmode', 'off')) %}
#          all
#        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.dining_lights_switch', 'off')) %}
#          off
#        {% else %}
#          failed
#        {% endif %}
#    kids_light_state:
#      friendly_name: "Kids light state"
#      value_template: >-
#        {% if (is_state('light.kids_left_lamp', 'on') and is_state('light.kids_right_lamp', 'off') and is_state('input_boolean.kids_nightmode', 'off')) %}
#          left_on
#        {% elif (is_state('light.kids_left_lamp', 'off') and is_state('light.kids_right_lamp', 'on') and is_state('input_boolean.kids_nightmode', 'off')) %}
#          right_on
#        {% elif (is_state('light.kids_left_lamp', 'off') and is_state('light.kids_right_lamp', 'on') and is_state('input_boolean.kids_nightmode', 'on')) %}
#          kids_nightmode
#        {% elif (is_state('light.kids_left_lamp', 'on') and is_state('light.kids_right_lamp', 'on') and is_state('input_boolean.kids_nightmode', 'off')) %}
#          all
#        {% elif (is_state('light.kids_left_lamp', 'off') and is_state('light.kids_right_lamp', 'off')) %}
#          off
#        {% else %}
#          failed
#        {% endif %}

#- platform: min_max
#  type: mean
#  name: Average house humidity
#  entity_ids:
#    - sensor.kids_multy_relative_humidity
#    - sensor.kitchen_multi_relative_humidity
#    - sensor.livingroom_multi_relative_humidity
#    - sensor.master_multi_relative_humidity

- platform: aarlo
  monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
