- platform: badnest

- platform: waze_travel_time
  name: "Nick to Work"
  origin: device_tracker.sm_g975u
  destination: zone.nick_work
  region: 'US'     

- platform: waze_travel_time
  name: "Nata to Work"
  origin: device_tracker.sm_n970u
  destination: zone.nata_work
  region: 'US'

- platform: waze_travel_time
  name: "Nick to Home"
  origin: device_tracker.sm_g975u
  destination: zone.home
  region: 'US'

- platform: waze_travel_time
  name: "Nata to Home"
  origin: device_tracker.sm_n970u
  destination: zone.home
  region: 'US'

- platform: min_max
  type: mean
  name: Average house temperature
  entity_ids:
    - sensor.kitchen_multi_temperature
    - sensor.livingroom_multi_temperature
    - sensor.kids_multy_temperature
    - sensor.master_multi_temperature

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, make sure configuration file is encoded as UTF-8
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: template
  sensors:
    nest_temperature:
      friendly_name: "Nest temperature"
      value_template: "{{ state_attr('climate.kitchen_thermostat', 'current_temperature') }}"
      device_class: temperature
      unit_of_measurement: °C

    nest_humidity:
      friendly_name: "Nest humidity"
      value_template: "{{ state_attr('climate.kitchen_thermostat', 'current_humidity') }}"
      device_class: humidity

- platform: smartweather
  wind_unit: kmh
  monitored_conditions:
    - temperature
    - feels_like_temperature
    - heat_index
    - wind_chill
    - dewpoint
    - wind_speed
    - wind_gust
    - wind_lull
    - wind_bearing
    - wind_direction
    - precipitation
    - precipitation_rate
    - precipitation_last_1hr
    - precipitation_yesterday
    - precip_minutes_local_day
    - precip_minutes_local_yesterday
    - humidity
    - pressure
    - uv
    - solar_radiation
    - illuminance
    - lightning_count