- platform: badnest

- platform: waze_travel_time
  name: "Nick to Work"
  origin: device_tracker.sm_g975u
  destination: zone.nick_work
  region: 'US'     

- platform: waze_travel_time
  name: "Nata to Work"
  origin: device_tracker.sm_n970u
  destination: zone.nata_work
  region: 'US'

- platform: waze_travel_time
  name: "Nick to Home"
  origin: device_tracker.sm_g975u
  destination: zone.home
  region: 'US'

- platform: waze_travel_time
  name: "Nata to Home"
  origin: device_tracker.sm_n970u
  destination: zone.home
  region: 'US'

- platform: min_max
  type: mean
  name: Average house temperature
  entity_ids:
    - sensor.kitchen_multi_temperature
    - sensor.livingroom_multi_temperature
    - sensor.kids_multy_temperature
    - sensor.master_multi_temperature

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, make sure configuration file is encoded as UTF-8
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: template
  sensors:
    nest_temperature:
      friendly_name: "Nest temperature"
      value_template: "{{ state_attr('climate.kitchen_thermostat', 'current_temperature') }}"
      device_class: temperature
      unit_of_measurement: °C

    nest_humidity:
      friendly_name: "Nest humidity"
      value_template: "{{ state_attr('climate.kitchen_thermostat', 'current_humidity') }}"
      device_class: humidity

    first_floor_lights:
      friendly_name: "First floor light state"
      value_template: >-
        {% if (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.kitchen_lights', 'off')) %}
          living_right_on
        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.kitchen_lights', 'off')) %}
          living_left_on
        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.kitchen_lights', 'off') and is_state('input_boolean.living_nightmode', 'on')) %}
          living_nightmode
        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.kitchen_lights', 'on') and is_state('input_boolean.living_nightmode', 'on')) %}
          kitchen_and_nightmode
        {% elif (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.kitchen_lights', 'off')) %}
          living_all
        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.kitchen_lights', 'on')) %}
          kitchen_on
        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.kitchen_lights', 'on')) %}
          kitchen_and_left_on
        {% elif (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.kitchen_lights', 'on')) %}
          kitchen_and_right_on
        {% elif (is_state('light.livingroom_right_lamp', 'on') and is_state('light.livingroom_left_lamp', 'on') and is_state('light.kitchen_lights', 'on')) %}
          all
        {% elif (is_state('light.livingroom_right_lamp', 'off') and is_state('light.livingroom_left_lamp', 'off') and is_state('light.kitchen_lights', 'off')) %}
          off
        {% else %}
          failed
        {% endif %}

- platform: smartweather
  wind_unit: kmh
  monitored_conditions:
    - temperature
    - feels_like_temperature
    - heat_index
    - wind_chill
    - dewpoint
    - wind_speed
    - wind_gust
    - wind_lull
    - wind_bearing
    - wind_direction
    - precipitation
    - precipitation_rate
    - precipitation_last_1hr
    - precipitation_yesterday
    - precip_minutes_local_day
    - precip_minutes_local_yesterday
    - humidity
    - pressure
    - uv
    - solar_radiation
    - illuminance
    - lightning_count