initial_state: 'on'
alias: Start climate when windows closed
description: ''
trigger:
  - entity_id: binary_sensor.all_windows_closed
    for: 00:00:15
    from: 'on'
    platform: state
    to: 'off'
action:
  - data: {}
    entity_id: climate.kitchen_thermostat
    service: climate.turn_on
  - entity_id: climate.kitchen_thermostat
    service_template: >
      {% if (state_attr('weather.openweathermap', 'temperature') < 15) %}
        script.climate_to_heat
      {% elif ((state_attr('weather.openweathermap', 'temperature') < 15) and (state_attr('weather.openweathermap', 'temperature') < 25)) %}
        script.climate_to_auto
      {% else %}
        script.climate_to_cool
      {% endif %}