initial_state: 'on'
alias: Start climate when windows closed
description: ''
trigger:
  - entity_id: binary_sensor.all_windows_closed
    for: 00:00:15
    from: 'on'
    platform: state
    to: 'off'
action:
  - entity_id: climate.kitchen_thermostat
    service_template: >
      {% if (states('sensor.smartweather_temperature') | int < 15) %}
        script.climate_to_heat
      {% elif ((states('sensor.smartweather_temperature') | int >= 15)  and (states('sensor.smartweather_temperature') | int < 25)) %}
        script.climate_to_auto
      {% else %}
        script.climate_to_cool
      {% endif %}