initial_state: 'on'
alias: Start ecomode when nobody home
description: ''
trigger:
  - entity_id: binary_sensor.athome
    from: 'on'
    platform: state
    to: 'off'
condition: []
action:
  - data:
      entity_id: climate.kitchen
      preset_mode: eco
    entity_id: climate.kitchen_thermostat
    service: climate.set_preset_mode