initial_state: 'on'
alias: Stop climate when windows open
description: ''
trigger:
  - entity_id: binary_sensor.all_windows_closed
    for: 00:00:15
    from: 'off'
    platform: state
    to: 'on'
action:
  - data: {}
    entity_id: climate.kitchen_thermostat
    service: climate.turn_off