alias: ALARM - CO Detected
description: ''
trigger:
  - entity_id: sensor.corridor_co_detector
    platform: state
  - entity_id: sensor.kitchen_co_detector
    platform: state
condition: []
action:
  - data:
      message: "<b>CO</b> detected in the <b>Kitchen or Corridor area</b>!"
      title: SMOKE Alarm!!!
      data:
        channel: Alarm
        importance: high           # set the channel importance to high
        ledColor: red              # make the LED flash red for this notification
        vibrationPattern: "1000,300,1000,300,1000,300,2000,300,2000,300,2000,300,1000,300,1000,300,1000"     # SOS vibration pattern
        persistent: true           # set to persistent
        sticky: true               # make sure it doesn't dismiss if selected
        clickAction: /lovelace/security    # navigate user to the lovelace alarm view
        icon: /local/images/alarm.png     # relative path to the icon
        color: red                 # set the color of the notification to red
        group: alarm               # the group name to group together notifications
        tag: alarm                 # tag is required in order to remove the persistent notification
    service: notify.mobile_app_nicksphone
  - data:
      message: "<b>CO</b> detected in the <b>Kitchen or Corridor area</b>!"
      title: SMOKE Alarm!!!
      data:
        channel: Alarm
        importance: high           # set the channel importance to high
        ledColor: red              # make the LED flash red for this notification
        vibrationPattern: "1000,300,1000,300,1000,300,2000,300,2000,300,2000,300,1000,300,1000,300,1000"     # SOS vibration pattern
        persistent: true           # set to persistent
        sticky: true               # make sure it doesn't dismiss if selected
        clickAction: /lovelace/security    # navigate user to the lovelace alarm view
        icon: /local/images/alarm.png     # relative path to the icon
        color: red                 # set the color of the notification to red
        group: alarm               # the group name to group together notifications
        tag: alarm                 # tag is required in order to remove the persistent notification
    service: notify.mobile_app_sm_n970u
mode: single
