alias: ALARM - Master Bathroom Leak Detected
description: ''
trigger:
- device_id: e5c43a27c4694bbeb759a2faeddf8c77
  domain: binary_sensor
  entity_id: binary_sensor.guest_bathroom_leak_sensor_water
  platform: device
  type: moist
condition: []
action:
  - data:
      message: "<b>Water</b> detected in the <b>Guest Bathroom area</b>!"
      title: LEAK Alarm!!!
      data:
        channel: Alarm
        importance: high           # set the channel importance to high
        ledColor: red              # make the LED flash red for this notification
        vibrationPattern: "1000,300,1000,300,1000,300,2000,300,2000,300,2000,300,1000,300,1000,300,1000"     # SOS vibration pattern
        persistent: true           # set to persistent
        sticky: true               # make sure it doesn't dismiss if selected
        clickAction: /lovelace/security    # navigate user to the lovelace alarm view
        icon: /local/images/alarm.png     # relative path to the icon
        color: red                 # set the color of the notification to red
        group: alarm               # the group name to group together notifications
        tag: alarm                 # tag is required in order to remove the persistent notification
    service: notify.mobile_app_nicksphone
  - data:
      message: Water detected in the Guest Bathroom area!
      title: LEAK Alarm!!!
    service: notify.mobile_app_sm_n970u
mode: single