alias: ALARM - Kitchen Leak Detected
description: ''
trigger:
- device_id: 73decac62d0945e6b6a5bf6bd539f5eb
  domain: binary_sensor
  entity_id: binary_sensor.kitchen_leak_sensor_water
  platform: device
  type: moist
condition: []
action:
  - data:
      message: Water detected in the Kitchen area!
      title: LEAK Alarm!!!
    service: notify.mobile_app_nicksphone
  - data:
      message: Water detected in the Kitchen area!
      title: LEAK Alarm!!!
    service: notify.mobile_app_sm_n970u
mode: single