alias: ALARM - Master Bathroom Leak Detected
description: ''
trigger:
- device_id: 2b7c68b18c56420abbeb6949a99396e7
  domain: binary_sensor
  entity_id: binary_sensor.master_bathroom_leak_sensor_water
  platform: device
  type: moist
condition: []
action:
  - data:
      message: Water detected in the Master Bathroom area!
      title: LEAK Alarm!!!
    service: notify.mobile_app_nicksphone
  - data:
      message: Water detected in the Master Bathroom area!
      title: LEAK Alarm!!!
    service: notify.mobile_app_sm_n970u
mode: single