alias: ALARM - Smoke Detected
description: ''
trigger:
  - entity_id: sensor.corridor_smoke_detector
    platform: state
  - entity_id: sensor.kitchen_smoke_detector
    platform: state
condition: []
action:
  - data:
      message: Smoke or Fire Detected in the Kitchen or Corridor area!
      title: SMOKE Alarm!!!
    service: notify.mobile_app_nicksphone
  - data:
      message: Smoke or Fire Detected in the Kitchen or Corridor area!
      title: SMOKE Alarm!!!
    service: notify.mobile_app_sm_n970u
mode: single
