initial_state: 'on'
alias: LIGHT ON Corridor night
description: ''
trigger:
  - device_id: 3bcc912ae2e347d3b1605d7a71e3042e
    domain: binary_sensor
    entity_id: binary_sensor.corridor_motion_sensor_motion
    platform: device
    type: motion
condition:
  - condition: and
    conditions:
      - after: '23:00:00'
        before: '6:00:00'
        condition: time
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'on'
          - condition: state
            entity_id: binary_sensor.athome
            state: 'on'
action:
  - scene: scene.corridor_night