initial_state: 'on'
alias: Master bedroom light auto turn on
description: ''
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'

  - platform: time_pattern
    minutes: "/1"

#  - platform: numeric_state
#    entity_id: sensor.master_multi_illuminance
#    below: 30
#    for:
#      hours: 0
#      minutes: 4
#      seconds: 0

condition:
  condition: numeric_state
  entity_id: sensor.master_multi_illuminance
  below: 30

action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.master_lights_auto