initial_state: 'off'
alias: LIGHT ON Master bedroom night
description: ''
trigger:
  - device_id: 957373b88c574e40bed5cbaa6d42df69
    domain: binary_sensor
    entity_id: binary_sensor.master_multi_motion
    platform: device
    type: motion
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.athome
        state: 'on'
      - condition: state
        entity_id: input_boolean.master_nightmode
        state: 'on'
      - condition: state
        entity_id: input_boolean.master_lights_auto
        state: 'on'
action:
  - entity_id: light.master_fan_1
    service: light.turn_on
