initial_state: 'off'
alias: LIGHT ON Master bedroom day
description: ''
trigger:
  - device_id: 957373b88c574e40bed5cbaa6d42df69
    domain: binary_sensor
    entity_id: binary_sensor.master_multi_motion
    platform: device
    type: motion
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.athome
        state: 'on'
      - condition: state
        entity_id: input_boolean.master_nightmode
        state: 'off'
      - condition: state
        entity_id: input_boolean.master_lights_auto
        state: 'on'
action:
  - data:
      entity_id: light.master_bedroom_lights
    entity_id: light.master_bedroom_lights
    service: light.turn_on