initial_state: 'on'
alias: Master bedroom auto turn off
description: ''
trigger:
  - platform: sun
    event: sunrise
    offset: '01:00:00'

  - platform: time_pattern
    minutes: "/5"

#  - platform: numeric_state
#    entity_id: sensor.master_multi_illuminance
#    above: 30
#    for:
#      hours: 0
#      minutes: 4
#      seconds: 0

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.master_bedroom_lights
      state: 'off'

    - condition: numeric_state
      entity_id: sensor.master_multi_illuminance
      above: 30

action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_lights_auto