initial_state: 'off'
alias: LIGHT OFF Master bedroom
description: ''
trigger:
  - device_id: 957373b88c574e40bed5cbaa6d42df69
    domain: binary_sensor
    entity_id: binary_sensor.master_multi_motion
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: no_motion
condition: []
action:
  - data:
      entity_id: light.master_bedroom_lights
    entity_id: light.master_bedroom_lights
    service: light.turn_off