initial_state: 'on'
alias: Master bedroom night mode turn on
description: ''
trigger:
  - at: '23:00'
    platform: time
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.master_nightmode