initial_state: 'on'
alias: Kitchen night mode turn on
description: ''
trigger:
  - at: '00:00'
    platform: time
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kitchen_nightmode