initial_state: 'on'
alias: Livingroom light auto turn on
description: ''
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'

  - platform: time_pattern
    minutes: "/5"

#  - platform: numeric_state
#    entity_id: sensor.livingroom_multi_illuminance
#    below: 5
#    for:
#      hours: 0
#      minutes: 4
#      seconds: 0

condition:
  condition: numeric_state
  entity_id: sensor.livingroom_multi_illuminance
  below: 5

action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.living_lights_auto