initial_state: 'on'
alias: LIGHT OFF Livingroom at night
description: ''
trigger:
  - device_id: 46e15b23d3894d08ab32b572d3ba1517
    domain: binary_sensor
    entity_id: binary_sensor.livingroom_multi_motion
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: no_motion

condition:
  condition: state
  entity_id: input_boolean.living_nightmode
  state: 'on'

action:
  - data:
      entity_id: light.living_room_lights
    entity_id: light.living_room_lights
    service: light.turn_off