initial_state: 'on'
alias: Livingroom light auto turn off
description: ''
trigger:
  - platform: sun
    event: sunrise
    offset: '01:00:00'
  - platform: numeric_state
    entity_id: sensor.livingroom_multi_illuminance
    above: 5
    for:
      hours: 0
      minutes: 4
      seconds: 0
condition:
  - condition: state
    entity_id: light.living_room_lights
    state: 'off'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.living_lights_auto