initial_state: 'on'
alias: Livingroom night mode turn off
description: ''
trigger:
  - event: sunrise
    platform: sun
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.living_nightmode