initial_state: 'on'
alias: LIGHT OFF kitchen at night
description: ''
trigger:
  - device_id: 84994766ffa24856ba202da1b2c6fb55
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_multi_motion
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: no_motion

condition:
  condition: state
  entity_id: input_boolean.kitchen_nightmode
  state: 'on'

action:
  - data:
      entity_id: light.dining_lights_switch
    entity_id: light.dining_lights_switch
    service: light.turn_off