initial_state: 'on'
alias: LIGHT OFF kitchen
description: ''
trigger:
  - device_id: 84994766ffa24856ba202da1b2c6fb55
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_multi_motion
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: no_motion
condition: []
action:
  - data:
      entity_id: light.kitchen_lights
    entity_id: light.kitchen_lights
    service: light.turn_off