initial_state: 'on'
alias: LIGHT ON kitchen night
description: ''
trigger:
  - device_id: 84994766ffa24856ba202da1b2c6fb55
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_multi_motion
    platform: device
    type: motion
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.athome
        state: 'on'
      - condition: state
        entity_id: input_boolean.kitchen_nightmode
        state: 'on'
      - condition: state
        entity_id: input_boolean.kitchen_lights_auto
        state: 'on'
action:
  - entity_id: light.66514121500291c7eb68
    service: light.turn_on
