initial_state: 'on'
alias: Kitchen light auto turn on
description: ''
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  - platform: numeric_state
    entity_id: sensor.kitchen_multi_illuminance
    below: 30
    for:
      hours: 0
      minutes: 4
      seconds: 0
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kitchen_lights_auto