initial_state: 'on'
alias: Kids night mode turn on
description: ''
trigger:
  - at: '21:30'
    platform: time
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kids_nightmode