initial_state: 'on'
alias: Kids light auto turn on
description: ''
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  - platform: numeric_state
    entity_id: sensor.kids_multy_illuminance
    below: 7
    for:
      hours: 0
      minutes: 4
      seconds: 0
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.kids_lights_auto