initial_state: 'on'
alias: LIGHTS OFF kids bedroom
description: ''
trigger:
  - device_id: 6bf1ac9817054053af1b191975cfb007
    domain: binary_sensor
    entity_id: binary_sensor.kids_multy_motion
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: no_motion
condition:
  - condition: state
    entity_id: input_boolean.kids_nightmode
    state: 'off'
action:
  - data:
      entity_id: light.kids_bedroom_lights
    entity_id: light.kids_bedroom_lights
    service: light.turn_off