initial_state: 'on'
alias: Kids light auto turn off
description: ''
trigger:
  - platform: sun
    event: sunrise
    offset: '01:00:00'

  - platform: time_pattern
    minutes: "/10"

#  - platform: numeric_state
#    entity_id: sensor.kids_multy_illuminance
#    above: 7
#    for:
#      hours: 0
#      minutes: 4
#      seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.kids_bedroom_lights
      state: 'off'

    - condition: numeric_state
      entity_id: sensor.kids_multy_illuminance
      above: 10

    - condition: state
      entity_id: input_boolean.kids_lights_auto
      state: 'on'

action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.kids_lights_auto