initial_state: 'on'
alias: Turn on kids night mode
description: ''
trigger:
  - at: '21:35'
    platform: time
condition:
  - condition: or
    conditions:
      - condition: zone
        entity_id: person.nata
        zone: zone.home
      - condition: zone
        entity_id: person.nick
        zone: zone.home
action:
  - scene: scene.kids_night_mode
  - entity_id: automation.lights_on_kids_bedroom
    service: automation.turn_off