initial_state: 'on'
alias: Turn on kids asleep lightning
description: ''
trigger:
  - platform: state
    entity_id: input_boolean.kids_nightmode
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.athome
    state: 'on'
action:
  - scene: scene.kids_night_mode
#  - entity_id: automation.lights_on_kids_bedroom
#    service: automation.turn_off